version: "3"
services:
  redis:
    image: redis
    ports:
      - "127.0.0.1:6378:6379"
    user: "redis:redis"
  postgres:
    image: postgres
    ports:
      - "127.0.0.1:5434:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: outline
    user: "postgres:postgres"
  outline:
      image: outlinewiki/outline
      ports:
        - "127.0.0.1:3000:3000"
      environment:
        DEBUG: "http"
        PORT: "3000"
        FILE_STORAGE_UPLOAD_MAX_SIZE: "80000000"
        FILE_STORAGE: "local"
        FILE_STORAGE_LOCAL_ROOT_DIR: "/var/lib/outline/data"
        FILE_STORAGE_IMPORT_MAX_SIZE: "80000000"
        FILE_STORAGE_WORKSPACE_IMPORT_MAX_SIZE: "80000000"
        PGSSLMODE: "disable"
        FORCE_HTTPS: "false"
        DATABASE_URL: "postgresql://user:pass@postgres/outline"
        UTILS_SECRET: "d4a9c66a4373a757a19aa63fc8989b67a4940d57fddc1c5a4ac0618b73fee256"
        SECRET_KEY: "d4a9c66a4373a757a19aa63fc8989b67a4940d57fddc1c5a4ac0618b73fee256"
        NODE_ENV: "production"
        LOG_LEVEL: "debug"
        URL: "http://localhost:3000"
        COLLABORATION_URL: "http://localhost:3000"
        REDIS_URL: "redis://redis:6379"
        OIDC_CLIENT_ID: "tLPokbXam9cjYhqPrvMBVlfAwrRlrZj9NjtJTA8X"
        OIDC_CLIENT_SECRET: "{PULL FROM HCP}"
        OIDC_AUTH_URI: "http://localhost:8080/login"
        OIDC_TOKEN_URI: "http://host.docker.internal:8080/token"
        OIDC_USERINFO_URI: "http://host.docker.internal:8080/userinfo"
        OIDC_LOGOUT_URI: "http://localhost:8080/end-session/"
        OIDC_DISPLAY_NAME: "java"
        OIDC_USERNAME_CLAIM: "email"
